### ISSUE TITLE
Add please timeline like and comment

### ISSUE THREAD

**Issue by thsanki** [xosad/igFame#1]
Can you add timeline like and comment..
Like i follow a person who just posted a photo and bot like and comment on that photo in just now..in 5 sec of posting of photos
If it possible then please add thos features..
And your bot is great

**Comment by kaex** [comment]
explain "timeline"

**Comment by thsanki** [comment]
Means i follow a people when he upload any photos..
Then bot like his photo and do a comment in just now..

**Comment by kaex** [comment]
That cannot be in this project, thanks for the feedback!
