### ISSUE TITLE
User Agents and IG Version

### ISSUE THREAD

**Issue by kaykyr** [xosad/igFame#3]
Hi! I was testing this code, and works pretty fine for like posts, but you intent to implement follow/unfollow also?

I saw that the user agent is an old iOS version running on iPad, do you intent to implement other devices and iOS versions?

The Instagram Version in this code is too old, any chance to update it?

I'll check better, and I'll try to implement more functions.

**Comment by kaex** [comment]
Planning to release a new version of this project with newer iOS version soon.
