### ISSUE TITLE
How to create new requests?

### ISSUE THREAD

**Issue by fgabrielbr** [xosad/igFame#5]
Hello! I saw that you're using iOS device to make requests to Instagram. You implemented the LIKE endpoint.

I can see all requests from Android app using Charles, but I'm not able to do the same with iOS.

Can you teach how to do this with iOS? So I can update this repo with more requests (follow/comment/direct/story looking/story voting/etc.).

**Comment by kaex** [comment]
Hey!, pretty neat tutorial here: https://www.cyclon3.com/bypass-instagram-ssl-certificate-pinning-for-ios you'll need to bypass ssl pinning to mitm the requests.
